### ISSUE TITLE
Open cash drawer endpoint

### ISSUE THREAD

**Issue by nono3551** [datapacsro/oec#17]
**Describe the bug**
Swagger documentation has invalid description for endpoint "openCashDrawer".

**To Reproduce**
Steps to reproduce:
1. Open Docs/index.html
2. In navigation menu click "openCashDrawer"

**Expected behavior**
Expected endpoint example URL: ""/{CashRegisterCode}/opencashdrawer/"

**Screenshots**
Current endpoint URL
![image](https://user-images.githubusercontent.com/17045368/76762517-b8688d80-6791-11ea-8b16-1ae3f3e8bb40.png)

**Comment by slado** [comment]
Opravene, dakujem za postreh.
